# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZ_NmPtjeok8jX5D-CM-h-edu7DJLKPt
"""

streamlit>=1.30.0
pandas>=2.1.0
matplotlib>=3.7.0
plotly>=5.18.0